### PR TITLE
Added perl 5.22 to Travis configuration

### PR DESCRIPTION
**Pull request by jonasbn**
Perl 5.22 is now available on Travis.

### CODE REVIEW

**Comment by oalders** [comment]
:+1:

**Comment by haarg** [comment]
Note that the travis setup being used here allows us to specify arbitrary perl versions even if Travis itself doesn't have them built.

**Comment by jonasbn** [comment]
Hi @haarg 

Sounds interesting, how do you go about that? - do you have additional CI platforms available or?

jonasbn

**Comment by haarg** [comment]
@jonasbn My [travis-perl helpers project](https://github.com/travis-perl/helpers) will automatically provide perl versions that Travis doesn't by default.  Commonly used versions are pre-built, and others will be compiled on demand.

**Pull request merged**
